"""Add new phase-related tables

Revision ID: ff243f94d1a3
Revises: 2bb9e5c407cc
Create Date: 2026-01-08 09:31:00.314028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff243f94d1a3'
down_revision = '2bb9e5c407cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_groups',
    sa.Column('phase_group_id', sa.Integer(), nullable=False),
    sa.Column('centroid', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('phase_group_id', sa.Integer(), nullable=True),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('phase_description', sa.Text(), nullable=True),
    sa.Column('time_start', sa.Float(), nullable=True),
    sa.Column('time_end', sa.Float(), nullable=True),
    sa.Column('view_start', sa.Integer(), nullable=True),
    sa.Column('view_end', sa.Integer(), nullable=True),
    sa.Column('like_start', sa.Integer(), nullable=True),
    sa.Column('like_end', sa.Integer(), nullable=True),
    sa.Column('delta_view', sa.Integer(), nullable=True),
    sa.Column('delta_like', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_group_best_phases',
    sa.Column('phase_group_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('view_velocity', sa.Float(), nullable=True),
    sa.Column('like_velocity', sa.Float(), nullable=True),
    sa.Column('like_per_viewer', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_group_id'], ['phase_groups.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_insights',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('phase_group_id', sa.UUID(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('need_update', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_group_id'], ['phase_groups.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_insights')
    op.drop_table('phase_group_best_phases')
    op.drop_table('phases')
    op.drop_table('phase_groups')
    # ### end Alembic commands ###
